export const GET_CART = "GET_CART";
export const GET_COUNTER_CART = "GET_COUNTER_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const COUNT_CART = "COUNT_CART";
export const DICREMENT_COUNT_CART = "DICREMENT_COUNT_CART";
export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART";


